name: VoidSkills
version: 1.0-SNAPSHOT
main: me.rxndmz.voidskills.VoidSkills
api-version: 1.13
author: Rxndmz
depend: [WorldEdit, WorldGuardEvents, WorldGuard, Vault, ActionBarAPI]
commands:
  Test:
    description: for testing
  ResetSkills:
    description: resets a players skills
  Skills:
    description: opens skill menu
  Enchanter:
    description: opens enchant menu